"""remove gstr2 invoice tables, add gstr2b_uploads

Revision ID: 248644e207e7
Revises: 36da67c3bf7a
Create Date: 2025-12-18 12:40:57.829316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '248644e207e7'
down_revision: Union[str, Sequence[str], None] = '36da67c3bf7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gstr2b_uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False, comment='GSTR2B | PURCHASE_REGISTER | RECONCILED_OUTPUT'),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False, comment='pending | processing | completed | failed'),
    sa.Column('file_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Sheet names, row counts, reconciliation summary, errors'),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upload_id')
    )
    op.create_index('ix_gstr2b_upload_status', 'gstr2b_uploads', ['status'], unique=False)
    op.create_index('ix_gstr2b_upload_type', 'gstr2b_uploads', ['file_type'], unique=False)
    op.create_index('ix_gstr2b_upload_user', 'gstr2b_uploads', ['user_id'], unique=False)
    op.create_index(op.f('ix_gstr2b_uploads_file_hash'), 'gstr2b_uploads', ['file_hash'], unique=False)
    op.create_index(op.f('ix_gstr2b_uploads_id'), 'gstr2b_uploads', ['id'], unique=False)
    op.create_index(op.f('ix_gstr2b_uploads_user_id'), 'gstr2b_uploads', ['user_id'], unique=False)
    
    op.drop_index(op.f('ix_recon_result_batch'), table_name='reconciliation_result')
    op.drop_index(op.f('ix_recon_result_gstr2b'), table_name='reconciliation_result')
    op.drop_index(op.f('ix_recon_result_purchase'), table_name='reconciliation_result')
    op.drop_index(op.f('ix_recon_result_review'), table_name='reconciliation_result')
    op.drop_index(op.f('ix_recon_result_score'), table_name='reconciliation_result')
    op.drop_index(op.f('ix_recon_result_status'), table_name='reconciliation_result')
    op.drop_index(op.f('ix_reconciliation_result_created_at'), table_name='reconciliation_result')
    op.drop_index(op.f('ix_reconciliation_result_gstr2b_invoice_id'), table_name='reconciliation_result')
    op.drop_index(op.f('ix_reconciliation_result_id'), table_name='reconciliation_result')
    op.drop_index(op.f('ix_reconciliation_result_manual_review_required'), table_name='reconciliation_result')
    op.drop_index(op.f('ix_reconciliation_result_match_score'), table_name='reconciliation_result')
    op.drop_index(op.f('ix_reconciliation_result_match_status'), table_name='reconciliation_result')
    op.drop_index(op.f('ix_reconciliation_result_purchase_invoice_id'), table_name='reconciliation_result')
    op.drop_index(op.f('ix_reconciliation_result_reconciliation_batch_id'), table_name='reconciliation_result')
    op.drop_index(op.f('ix_reconciliation_result_user_id'), table_name='reconciliation_result')
    op.drop_table('reconciliation_result')
    op.drop_index(op.f('ix_recon_batch_created'), table_name='reconciliation_batch')
    op.drop_index(op.f('ix_recon_batch_gstr2b'), table_name='reconciliation_batch')
    op.drop_index(op.f('ix_recon_batch_purchase'), table_name='reconciliation_batch')
    op.drop_index(op.f('ix_recon_batch_status'), table_name='reconciliation_batch')
    op.drop_index(op.f('ix_recon_batch_user'), table_name='reconciliation_batch')
    op.drop_index(op.f('ix_reconciliation_batch_gstr2b_upload_id'), table_name='reconciliation_batch')
    op.drop_index(op.f('ix_reconciliation_batch_purchase_upload_id'), table_name='reconciliation_batch')
    op.drop_index(op.f('ix_reconciliation_batch_user_id'), table_name='reconciliation_batch')
    op.drop_table('reconciliation_batch')
    op.drop_index(op.f('ix_gstr2b_gstin_invno_date'), table_name='gstr2b_invoice')
    op.drop_index(op.f('ix_gstr2b_invoice_file_hash'), table_name='gstr2b_invoice')
    op.drop_index(op.f('ix_gstr2b_invoice_gstin'), table_name='gstr2b_invoice')
    op.drop_index(op.f('ix_gstr2b_invoice_id'), table_name='gstr2b_invoice')
    op.drop_index(op.f('ix_gstr2b_invoice_invoice_date'), table_name='gstr2b_invoice')
    op.drop_index(op.f('ix_gstr2b_invoice_invoice_number'), table_name='gstr2b_invoice')
    op.drop_index(op.f('ix_gstr2b_invoice_invoice_number_normalized'), table_name='gstr2b_invoice')
    op.drop_index(op.f('ix_gstr2b_invoice_matched'), table_name='gstr2b_invoice')
    op.drop_index(op.f('ix_gstr2b_invoice_sheet_name'), table_name='gstr2b_invoice')
    op.drop_index(op.f('ix_gstr2b_invoice_sheet_type'), table_name='gstr2b_invoice')
    op.drop_index(op.f('ix_gstr2b_invoice_upload_id'), table_name='gstr2b_invoice')
    op.drop_index(op.f('ix_gstr2b_invoice_user_id'), table_name='gstr2b_invoice')
    op.drop_index(op.f('ix_gstr2b_matched_status'), table_name='gstr2b_invoice')
    op.drop_index(op.f('ix_gstr2b_upload_matched'), table_name='gstr2b_invoice')
    op.drop_table('gstr2b_invoice')
    op.drop_index(op.f('ix_purchase_gstin_invno_date'), table_name='purchase_register_invoice')
    op.drop_index(op.f('ix_purchase_matched_status'), table_name='purchase_register_invoice')
    op.drop_index(op.f('ix_purchase_register_invoice_file_hash'), table_name='purchase_register_invoice')
    op.drop_index(op.f('ix_purchase_register_invoice_id'), table_name='purchase_register_invoice')
    op.drop_index(op.f('ix_purchase_register_invoice_invoice_date'), table_name='purchase_register_invoice')
    op.drop_index(op.f('ix_purchase_register_invoice_invoice_number'), table_name='purchase_register_invoice')
    op.drop_index(op.f('ix_purchase_register_invoice_invoice_number_normalized'), table_name='purchase_register_invoice')
    op.drop_index(op.f('ix_purchase_register_invoice_matched'), table_name='purchase_register_invoice')
    op.drop_index(op.f('ix_purchase_register_invoice_supplier_gstin'), table_name='purchase_register_invoice')
    op.drop_index(op.f('ix_purchase_register_invoice_upload_id'), table_name='purchase_register_invoice')
    op.drop_index(op.f('ix_purchase_register_invoice_user_id'), table_name='purchase_register_invoice')
    op.drop_index(op.f('ix_purchase_upload_matched'), table_name='purchase_register_invoice')
    op.drop_table('purchase_register_invoice')
    op.drop_index(op.f('ix_config_default'), table_name='gstr2_configuration')
    op.drop_index(op.f('ix_config_user'), table_name='gstr2_configuration')
    op.drop_index(op.f('ix_gstr2_configuration_id'), table_name='gstr2_configuration')
    op.drop_index(op.f('ix_gstr2_configuration_user_id'), table_name='gstr2_configuration')
    op.drop_table('gstr2_configuration')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gstr2_configuration',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('config_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('config_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('is_default', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('gstr2_configuration_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('gstr2_configuration_pkey')),
    sa.UniqueConstraint('user_id', 'config_name', name=op.f('uq_config_name_per_user'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_gstr2_configuration_user_id'), 'gstr2_configuration', ['user_id'], unique=False)
    op.create_index(op.f('ix_gstr2_configuration_id'), 'gstr2_configuration', ['id'], unique=False)
    op.create_index(op.f('ix_config_user'), 'gstr2_configuration', ['user_id'], unique=False)
    op.create_index(op.f('ix_config_default'), 'gstr2_configuration', ['user_id', 'is_default'], unique=False)
    op.create_table('purchase_register_invoice',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('purchase_register_invoice_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('upload_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('supplier_gstin', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('supplier_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('invoice_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('invoice_number_normalized', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('invoice_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('invoice_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('invoice_date_normalized', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('invoice_value', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('taxable_value', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('igst', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('cgst', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('sgst', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('cess', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('total_tax', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('place_of_supply', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('reverse_charge_applicable', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('po_reference', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('payment_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('book_reference', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('column_mapping', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('data_quality_issues', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('file_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('matched', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('match_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('parsed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.CheckConstraint("supplier_gstin::text ~ '^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$'::text", name='ck_purchase_gstin_format'),
    sa.CheckConstraint('cess >= 0::numeric', name='ck_purchase_cess_positive'),
    sa.CheckConstraint('cgst >= 0::numeric', name='ck_purchase_cgst_positive'),
    sa.CheckConstraint('igst >= 0::numeric', name='ck_purchase_igst_positive'),
    sa.CheckConstraint('sgst >= 0::numeric', name='ck_purchase_sgst_positive'),
    sa.CheckConstraint('taxable_value >= 0::numeric', name='ck_purchase_taxable_positive'),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], name='purchase_register_invoice_upload_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='purchase_register_invoice_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='purchase_register_invoice_pkey'),
    sa.UniqueConstraint('upload_id', 'supplier_gstin', 'invoice_number_normalized', 'invoice_date', name='uq_purchase_unique_invoice', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_purchase_upload_matched'), 'purchase_register_invoice', ['upload_id', 'matched'], unique=False)
    op.create_index(op.f('ix_purchase_register_invoice_user_id'), 'purchase_register_invoice', ['user_id'], unique=False)
    op.create_index(op.f('ix_purchase_register_invoice_upload_id'), 'purchase_register_invoice', ['upload_id'], unique=False)
    op.create_index(op.f('ix_purchase_register_invoice_supplier_gstin'), 'purchase_register_invoice', ['supplier_gstin'], unique=False)
    op.create_index(op.f('ix_purchase_register_invoice_matched'), 'purchase_register_invoice', ['matched'], unique=False)
    op.create_index(op.f('ix_purchase_register_invoice_invoice_number_normalized'), 'purchase_register_invoice', ['invoice_number_normalized'], unique=False)
    op.create_index(op.f('ix_purchase_register_invoice_invoice_number'), 'purchase_register_invoice', ['invoice_number'], unique=False)
    op.create_index(op.f('ix_purchase_register_invoice_invoice_date'), 'purchase_register_invoice', ['invoice_date'], unique=False)
    op.create_index(op.f('ix_purchase_register_invoice_id'), 'purchase_register_invoice', ['id'], unique=False)
    op.create_index(op.f('ix_purchase_register_invoice_file_hash'), 'purchase_register_invoice', ['file_hash'], unique=False)
    op.create_index(op.f('ix_purchase_matched_status'), 'purchase_register_invoice', ['matched', 'match_status'], unique=False)
    op.create_index(op.f('ix_purchase_gstin_invno_date'), 'purchase_register_invoice', ['supplier_gstin', 'invoice_number_normalized', 'invoice_date'], unique=False)
    op.create_table('gstr2b_invoice',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('gstr2b_invoice_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('upload_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('gstin', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('supplier_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('invoice_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('invoice_number_normalized', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('invoice_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('invoice_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('invoice_date_normalized', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('invoice_value', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('taxable_value', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('igst', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('cgst', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('sgst', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('cess', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('total_tax', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('place_of_supply', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('reverse_charge_applicable', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('itc_eligible', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('itc_availability_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('reason_for_exemption', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('gstr1_period', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('gstr1_filing_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('applicable_tax_rate', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('irn', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('irn_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('portal_document_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('file_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('matched', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('match_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('parsed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('sheet_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='Exact Excel sheet name from GSTR-2B template'),
    sa.Column('sheet_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='Normalized GSTR-2B sheet type (enum-based)'),
    sa.CheckConstraint("gstin::text ~ '^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$'::text", name='ck_gstr2b_gstin_format'),
    sa.CheckConstraint('cess >= 0::numeric', name='ck_gstr2b_cess_positive'),
    sa.CheckConstraint('cgst >= 0::numeric', name='ck_gstr2b_cgst_positive'),
    sa.CheckConstraint('igst >= 0::numeric', name='ck_gstr2b_igst_positive'),
    sa.CheckConstraint('sgst >= 0::numeric', name='ck_gstr2b_sgst_positive'),
    sa.CheckConstraint('taxable_value >= 0::numeric', name='ck_gstr2b_taxable_positive'),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], name='gstr2b_invoice_upload_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='gstr2b_invoice_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='gstr2b_invoice_pkey'),
    sa.UniqueConstraint('upload_id', 'gstin', 'invoice_number_normalized', 'invoice_date', name='uq_gstr2b_unique_invoice', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_gstr2b_upload_matched'), 'gstr2b_invoice', ['upload_id', 'matched'], unique=False)
    op.create_index(op.f('ix_gstr2b_matched_status'), 'gstr2b_invoice', ['matched', 'match_status'], unique=False)
    op.create_index(op.f('ix_gstr2b_invoice_user_id'), 'gstr2b_invoice', ['user_id'], unique=False)
    op.create_index(op.f('ix_gstr2b_invoice_upload_id'), 'gstr2b_invoice', ['upload_id'], unique=False)
    op.create_index(op.f('ix_gstr2b_invoice_sheet_type'), 'gstr2b_invoice', ['sheet_type'], unique=False)
    op.create_index(op.f('ix_gstr2b_invoice_sheet_name'), 'gstr2b_invoice', ['sheet_name'], unique=False)
    op.create_index(op.f('ix_gstr2b_invoice_matched'), 'gstr2b_invoice', ['matched'], unique=False)
    op.create_index(op.f('ix_gstr2b_invoice_invoice_number_normalized'), 'gstr2b_invoice', ['invoice_number_normalized'], unique=False)
    op.create_index(op.f('ix_gstr2b_invoice_invoice_number'), 'gstr2b_invoice', ['invoice_number'], unique=False)
    op.create_index(op.f('ix_gstr2b_invoice_invoice_date'), 'gstr2b_invoice', ['invoice_date'], unique=False)
    op.create_index(op.f('ix_gstr2b_invoice_id'), 'gstr2b_invoice', ['id'], unique=False)
    op.create_index(op.f('ix_gstr2b_invoice_gstin'), 'gstr2b_invoice', ['gstin'], unique=False)
    op.create_index(op.f('ix_gstr2b_invoice_file_hash'), 'gstr2b_invoice', ['file_hash'], unique=False)
    op.create_index(op.f('ix_gstr2b_gstin_invno_date'), 'gstr2b_invoice', ['gstin', 'invoice_number_normalized', 'invoice_date'], unique=False)
    op.create_table('reconciliation_result',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('gstr2b_invoice_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('purchase_invoice_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reconciliation_batch_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('manual_reviewed_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('match_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('match_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('match_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stage_reached', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('gstin_match', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('invoice_no_similarity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('invoice_no_is_substring', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('date_difference_days', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_match', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('taxable_value_difference', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('taxable_value_match', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('tax_component_differences', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('total_discrepancies', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('discrepancy_details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('reconciliation_notes', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('manual_review_required', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('manual_review_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('manual_review_notes', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('manual_reviewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.CheckConstraint('gstr2b_invoice_id IS NOT NULL OR purchase_invoice_id IS NOT NULL', name=op.f('ck_recon_at_least_one_invoice')),
    sa.CheckConstraint('match_score >= 0 AND match_score <= 100', name=op.f('ck_match_score_range')),
    sa.ForeignKeyConstraint(['gstr2b_invoice_id'], ['gstr2b_invoice.id'], name=op.f('reconciliation_result_gstr2b_invoice_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manual_reviewed_by'], ['users.id'], name=op.f('reconciliation_result_manual_reviewed_by_fkey')),
    sa.ForeignKeyConstraint(['purchase_invoice_id'], ['purchase_register_invoice.id'], name=op.f('reconciliation_result_purchase_invoice_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reconciliation_batch_id'], ['reconciliation_batch.id'], name=op.f('reconciliation_result_reconciliation_batch_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('reconciliation_result_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('reconciliation_result_pkey')),
    sa.UniqueConstraint('reconciliation_batch_id', 'gstr2b_invoice_id', 'purchase_invoice_id', name=op.f('uq_recon_result_unique'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_reconciliation_result_user_id'), 'reconciliation_result', ['user_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_result_reconciliation_batch_id'), 'reconciliation_result', ['reconciliation_batch_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_result_purchase_invoice_id'), 'reconciliation_result', ['purchase_invoice_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_result_match_status'), 'reconciliation_result', ['match_status'], unique=False)
    op.create_index(op.f('ix_reconciliation_result_match_score'), 'reconciliation_result', ['match_score'], unique=False)
    op.create_index(op.f('ix_reconciliation_result_manual_review_required'), 'reconciliation_result', ['manual_review_required'], unique=False)
    op.create_index(op.f('ix_reconciliation_result_id'), 'reconciliation_result', ['id'], unique=False)
    op.create_index(op.f('ix_reconciliation_result_gstr2b_invoice_id'), 'reconciliation_result', ['gstr2b_invoice_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_result_created_at'), 'reconciliation_result', ['created_at'], unique=False)
    op.create_index(op.f('ix_recon_result_status'), 'reconciliation_result', ['match_status'], unique=False)
    op.create_index(op.f('ix_recon_result_score'), 'reconciliation_result', ['match_score'], unique=False)
    op.create_index(op.f('ix_recon_result_review'), 'reconciliation_result', ['manual_review_required', 'manual_review_status'], unique=False)
    op.create_index(op.f('ix_recon_result_purchase'), 'reconciliation_result', ['purchase_invoice_id'], unique=False)
    op.create_index(op.f('ix_recon_result_gstr2b'), 'reconciliation_result', ['gstr2b_invoice_id'], unique=False)
    op.create_index(op.f('ix_recon_result_batch'), 'reconciliation_result', ['reconciliation_batch_id'], unique=False)
    op.create_table('reconciliation_batch',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('gstr2b_upload_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('purchase_upload_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('progress_percentage', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_gstr2b_invoices', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_purchase_invoices', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('exact_matches_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('probable_matches_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mismatches_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('missing_in_2b_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('missing_in_books_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('match_rate_percentage', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('matching_parameters', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('error_summary', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('report_file_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['gstr2b_upload_id'], ['uploads.id'], name=op.f('reconciliation_batch_gstr2b_upload_id_fkey')),
    sa.ForeignKeyConstraint(['purchase_upload_id'], ['uploads.id'], name=op.f('reconciliation_batch_purchase_upload_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('reconciliation_batch_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('reconciliation_batch_pkey'))
    )
    op.create_index(op.f('ix_reconciliation_batch_user_id'), 'reconciliation_batch', ['user_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_batch_purchase_upload_id'), 'reconciliation_batch', ['purchase_upload_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_batch_gstr2b_upload_id'), 'reconciliation_batch', ['gstr2b_upload_id'], unique=False)
    op.create_index(op.f('ix_recon_batch_user'), 'reconciliation_batch', ['user_id'], unique=False)
    op.create_index(op.f('ix_recon_batch_status'), 'reconciliation_batch', ['status'], unique=False)
    op.create_index(op.f('ix_recon_batch_purchase'), 'reconciliation_batch', ['purchase_upload_id'], unique=False)
    op.create_index(op.f('ix_recon_batch_gstr2b'), 'reconciliation_batch', ['gstr2b_upload_id'], unique=False)
    op.create_index(op.f('ix_recon_batch_created'), 'reconciliation_batch', ['created_at'], unique=False)
    op.drop_index(op.f('ix_gstr2b_uploads_user_id'), table_name='gstr2b_uploads')
    op.drop_index(op.f('ix_gstr2b_uploads_id'), table_name='gstr2b_uploads')
    op.drop_index(op.f('ix_gstr2b_uploads_file_hash'), table_name='gstr2b_uploads')
    op.drop_index('ix_gstr2b_upload_user', table_name='gstr2b_uploads')
    op.drop_index('ix_gstr2b_upload_type', table_name='gstr2b_uploads')
    op.drop_index('ix_gstr2b_upload_status', table_name='gstr2b_uploads')
    op.drop_table('gstr2b_uploads')
    # ### end Alembic commands ###
