"""add sheet_name and sheet_type to gstr2b_invoice

Revision ID: 36da67c3bf7a
Revises: a3d6e6053785
Create Date: 2025-12-18 12:09:31.104191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36da67c3bf7a'
down_revision: Union[str, Sequence[str], None] = 'a3d6e6053785'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gstr2b_invoice', sa.Column('sheet_name', sa.String(length=100), nullable=False, comment='Exact Excel sheet name from GSTR-2B template'))
    op.add_column('gstr2b_invoice', sa.Column('sheet_type', sa.String(length=50), nullable=False, comment='Normalized GSTR-2B sheet type (enum-based)'))
    op.create_index(op.f('ix_gstr2b_invoice_sheet_name'), 'gstr2b_invoice', ['sheet_name'], unique=False)
    op.create_index(op.f('ix_gstr2b_invoice_sheet_type'), 'gstr2b_invoice', ['sheet_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gstr2b_invoice_sheet_type'), table_name='gstr2b_invoice')
    op.drop_index(op.f('ix_gstr2b_invoice_sheet_name'), table_name='gstr2b_invoice')
    op.drop_column('gstr2b_invoice', 'sheet_type')
    op.drop_column('gstr2b_invoice', 'sheet_name')
    # ### end Alembic commands ###
