"""create all gstr2 models - complete

Revision ID: a3d6e6053785
Revises: 5a3b0080f4da
Create Date: 2025-12-15 21:26:39.930144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3d6e6053785'
down_revision: Union[str, Sequence[str], None] = '5a3b0080f4da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gstr2_configuration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('config_name', sa.String(length=100), nullable=False),
    sa.Column('config_type', sa.String(length=50), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'config_name', name='uq_config_name_per_user')
    )
    op.create_index('ix_config_default', 'gstr2_configuration', ['user_id', 'is_default'], unique=False)
    op.create_index('ix_config_user', 'gstr2_configuration', ['user_id'], unique=False)
    op.create_index(op.f('ix_gstr2_configuration_id'), 'gstr2_configuration', ['id'], unique=False)
    op.create_index(op.f('ix_gstr2_configuration_user_id'), 'gstr2_configuration', ['user_id'], unique=False)
    op.create_table('gstr2b_invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=True),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('invoice_number_normalized', sa.String(length=50), nullable=False),
    sa.Column('invoice_type', sa.String(length=20), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('invoice_date_normalized', sa.Date(), nullable=False),
    sa.Column('invoice_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('taxable_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('igst', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('cgst', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('sgst', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('cess', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_tax', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('place_of_supply', sa.String(length=100), nullable=True),
    sa.Column('reverse_charge_applicable', sa.Boolean(), nullable=False),
    sa.Column('itc_eligible', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('itc_availability_status', sa.String(length=50), nullable=True),
    sa.Column('reason_for_exemption', sa.String(length=255), nullable=True),
    sa.Column('gstr1_period', sa.String(length=20), nullable=True),
    sa.Column('gstr1_filing_date', sa.Date(), nullable=True),
    sa.Column('applicable_tax_rate', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('irn', sa.String(length=64), nullable=True),
    sa.Column('irn_date', sa.Date(), nullable=True),
    sa.Column('portal_document_type', sa.String(length=50), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('matched', sa.Boolean(), nullable=False),
    sa.Column('match_status', sa.String(length=50), nullable=True),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("gstin ~ '^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$'", name='ck_gstr2b_gstin_format'),
    sa.CheckConstraint('cess >= 0', name='ck_gstr2b_cess_positive'),
    sa.CheckConstraint('cgst >= 0', name='ck_gstr2b_cgst_positive'),
    sa.CheckConstraint('igst >= 0', name='ck_gstr2b_igst_positive'),
    sa.CheckConstraint('sgst >= 0', name='ck_gstr2b_sgst_positive'),
    sa.CheckConstraint('taxable_value >= 0', name='ck_gstr2b_taxable_positive'),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upload_id', 'gstin', 'invoice_number_normalized', 'invoice_date', name='uq_gstr2b_unique_invoice')
    )
    op.create_index('ix_gstr2b_gstin_invno_date', 'gstr2b_invoice', ['gstin', 'invoice_number_normalized', 'invoice_date'], unique=False)
    op.create_index(op.f('ix_gstr2b_invoice_file_hash'), 'gstr2b_invoice', ['file_hash'], unique=False)
    op.create_index(op.f('ix_gstr2b_invoice_gstin'), 'gstr2b_invoice', ['gstin'], unique=False)
    op.create_index(op.f('ix_gstr2b_invoice_id'), 'gstr2b_invoice', ['id'], unique=False)
    op.create_index(op.f('ix_gstr2b_invoice_invoice_date'), 'gstr2b_invoice', ['invoice_date'], unique=False)
    op.create_index(op.f('ix_gstr2b_invoice_invoice_number'), 'gstr2b_invoice', ['invoice_number'], unique=False)
    op.create_index(op.f('ix_gstr2b_invoice_invoice_number_normalized'), 'gstr2b_invoice', ['invoice_number_normalized'], unique=False)
    op.create_index(op.f('ix_gstr2b_invoice_matched'), 'gstr2b_invoice', ['matched'], unique=False)
    op.create_index(op.f('ix_gstr2b_invoice_upload_id'), 'gstr2b_invoice', ['upload_id'], unique=False)
    op.create_index(op.f('ix_gstr2b_invoice_user_id'), 'gstr2b_invoice', ['user_id'], unique=False)
    op.create_index('ix_gstr2b_matched_status', 'gstr2b_invoice', ['matched', 'match_status'], unique=False)
    op.create_index('ix_gstr2b_upload_matched', 'gstr2b_invoice', ['upload_id', 'matched'], unique=False)
    op.create_table('purchase_register_invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('supplier_gstin', sa.String(length=15), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=True),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('invoice_number_normalized', sa.String(length=50), nullable=False),
    sa.Column('invoice_type', sa.String(length=50), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('invoice_date_normalized', sa.Date(), nullable=False),
    sa.Column('invoice_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('taxable_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('igst', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('cgst', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('sgst', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('cess', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_tax', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('place_of_supply', sa.String(length=100), nullable=True),
    sa.Column('reverse_charge_applicable', sa.Boolean(), nullable=True),
    sa.Column('po_reference', sa.String(length=100), nullable=True),
    sa.Column('payment_status', sa.String(length=50), nullable=True),
    sa.Column('book_reference', sa.String(length=100), nullable=True),
    sa.Column('column_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('data_quality_issues', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('matched', sa.Boolean(), nullable=False),
    sa.Column('match_status', sa.String(length=50), nullable=True),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("supplier_gstin ~ '^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$'", name='ck_purchase_gstin_format'),
    sa.CheckConstraint('cess >= 0', name='ck_purchase_cess_positive'),
    sa.CheckConstraint('cgst >= 0', name='ck_purchase_cgst_positive'),
    sa.CheckConstraint('igst >= 0', name='ck_purchase_igst_positive'),
    sa.CheckConstraint('sgst >= 0', name='ck_purchase_sgst_positive'),
    sa.CheckConstraint('taxable_value >= 0', name='ck_purchase_taxable_positive'),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upload_id', 'supplier_gstin', 'invoice_number_normalized', 'invoice_date', name='uq_purchase_unique_invoice')
    )
    op.create_index('ix_purchase_gstin_invno_date', 'purchase_register_invoice', ['supplier_gstin', 'invoice_number_normalized', 'invoice_date'], unique=False)
    op.create_index('ix_purchase_matched_status', 'purchase_register_invoice', ['matched', 'match_status'], unique=False)
    op.create_index(op.f('ix_purchase_register_invoice_file_hash'), 'purchase_register_invoice', ['file_hash'], unique=False)
    op.create_index(op.f('ix_purchase_register_invoice_id'), 'purchase_register_invoice', ['id'], unique=False)
    op.create_index(op.f('ix_purchase_register_invoice_invoice_date'), 'purchase_register_invoice', ['invoice_date'], unique=False)
    op.create_index(op.f('ix_purchase_register_invoice_invoice_number'), 'purchase_register_invoice', ['invoice_number'], unique=False)
    op.create_index(op.f('ix_purchase_register_invoice_invoice_number_normalized'), 'purchase_register_invoice', ['invoice_number_normalized'], unique=False)
    op.create_index(op.f('ix_purchase_register_invoice_matched'), 'purchase_register_invoice', ['matched'], unique=False)
    op.create_index(op.f('ix_purchase_register_invoice_supplier_gstin'), 'purchase_register_invoice', ['supplier_gstin'], unique=False)
    op.create_index(op.f('ix_purchase_register_invoice_upload_id'), 'purchase_register_invoice', ['upload_id'], unique=False)
    op.create_index(op.f('ix_purchase_register_invoice_user_id'), 'purchase_register_invoice', ['user_id'], unique=False)
    op.create_index('ix_purchase_upload_matched', 'purchase_register_invoice', ['upload_id', 'matched'], unique=False)
    op.create_table('reconciliation_batch',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gstr2b_upload_id', sa.Integer(), nullable=False),
    sa.Column('purchase_upload_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress_percentage', sa.Integer(), nullable=True),
    sa.Column('total_gstr2b_invoices', sa.Integer(), nullable=True),
    sa.Column('total_purchase_invoices', sa.Integer(), nullable=True),
    sa.Column('exact_matches_count', sa.Integer(), nullable=True),
    sa.Column('probable_matches_count', sa.Integer(), nullable=True),
    sa.Column('mismatches_count', sa.Integer(), nullable=True),
    sa.Column('missing_in_2b_count', sa.Integer(), nullable=True),
    sa.Column('missing_in_books_count', sa.Integer(), nullable=True),
    sa.Column('match_rate_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('matching_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('report_file_path', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['gstr2b_upload_id'], ['uploads.id'], ),
    sa.ForeignKeyConstraint(['purchase_upload_id'], ['uploads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recon_batch_created', 'reconciliation_batch', ['created_at'], unique=False)
    op.create_index('ix_recon_batch_gstr2b', 'reconciliation_batch', ['gstr2b_upload_id'], unique=False)
    op.create_index('ix_recon_batch_purchase', 'reconciliation_batch', ['purchase_upload_id'], unique=False)
    op.create_index('ix_recon_batch_status', 'reconciliation_batch', ['status'], unique=False)
    op.create_index('ix_recon_batch_user', 'reconciliation_batch', ['user_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_batch_gstr2b_upload_id'), 'reconciliation_batch', ['gstr2b_upload_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_batch_purchase_upload_id'), 'reconciliation_batch', ['purchase_upload_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_batch_user_id'), 'reconciliation_batch', ['user_id'], unique=False)
    op.create_table('reconciliation_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gstr2b_invoice_id', sa.Integer(), nullable=True),
    sa.Column('purchase_invoice_id', sa.Integer(), nullable=True),
    sa.Column('reconciliation_batch_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('manual_reviewed_by', sa.Integer(), nullable=True),
    sa.Column('match_type', sa.String(length=50), nullable=False),
    sa.Column('match_status', sa.String(length=50), nullable=False),
    sa.Column('match_score', sa.Integer(), nullable=False),
    sa.Column('stage_reached', sa.String(length=50), nullable=False),
    sa.Column('gstin_match', sa.Boolean(), nullable=True),
    sa.Column('invoice_no_similarity', sa.Integer(), nullable=True),
    sa.Column('invoice_no_is_substring', sa.Boolean(), nullable=True),
    sa.Column('date_difference_days', sa.Integer(), nullable=True),
    sa.Column('date_match', sa.Boolean(), nullable=True),
    sa.Column('taxable_value_difference', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('taxable_value_match', sa.Boolean(), nullable=True),
    sa.Column('tax_component_differences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_discrepancies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('discrepancy_details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reconciliation_notes', sa.String(length=500), nullable=True),
    sa.Column('manual_review_required', sa.Boolean(), nullable=False),
    sa.Column('manual_review_status', sa.String(length=50), nullable=True),
    sa.Column('manual_review_notes', sa.String(length=500), nullable=True),
    sa.Column('manual_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(gstr2b_invoice_id IS NOT NULL OR purchase_invoice_id IS NOT NULL)', name='ck_recon_at_least_one_invoice'),
    sa.CheckConstraint('match_score >= 0 AND match_score <= 100', name='ck_match_score_range'),
    sa.ForeignKeyConstraint(['gstr2b_invoice_id'], ['gstr2b_invoice.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manual_reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['purchase_invoice_id'], ['purchase_register_invoice.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reconciliation_batch_id'], ['reconciliation_batch.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reconciliation_batch_id', 'gstr2b_invoice_id', 'purchase_invoice_id', name='uq_recon_result_unique')
    )
    op.create_index('ix_recon_result_batch', 'reconciliation_result', ['reconciliation_batch_id'], unique=False)
    op.create_index('ix_recon_result_gstr2b', 'reconciliation_result', ['gstr2b_invoice_id'], unique=False)
    op.create_index('ix_recon_result_purchase', 'reconciliation_result', ['purchase_invoice_id'], unique=False)
    op.create_index('ix_recon_result_review', 'reconciliation_result', ['manual_review_required', 'manual_review_status'], unique=False)
    op.create_index('ix_recon_result_score', 'reconciliation_result', ['match_score'], unique=False)
    op.create_index('ix_recon_result_status', 'reconciliation_result', ['match_status'], unique=False)
    op.create_index(op.f('ix_reconciliation_result_created_at'), 'reconciliation_result', ['created_at'], unique=False)
    op.create_index(op.f('ix_reconciliation_result_gstr2b_invoice_id'), 'reconciliation_result', ['gstr2b_invoice_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_result_id'), 'reconciliation_result', ['id'], unique=False)
    op.create_index(op.f('ix_reconciliation_result_manual_review_required'), 'reconciliation_result', ['manual_review_required'], unique=False)
    op.create_index(op.f('ix_reconciliation_result_match_score'), 'reconciliation_result', ['match_score'], unique=False)
    op.create_index(op.f('ix_reconciliation_result_match_status'), 'reconciliation_result', ['match_status'], unique=False)
    op.create_index(op.f('ix_reconciliation_result_purchase_invoice_id'), 'reconciliation_result', ['purchase_invoice_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_result_reconciliation_batch_id'), 'reconciliation_result', ['reconciliation_batch_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_result_user_id'), 'reconciliation_result', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reconciliation_result_user_id'), table_name='reconciliation_result')
    op.drop_index(op.f('ix_reconciliation_result_reconciliation_batch_id'), table_name='reconciliation_result')
    op.drop_index(op.f('ix_reconciliation_result_purchase_invoice_id'), table_name='reconciliation_result')
    op.drop_index(op.f('ix_reconciliation_result_match_status'), table_name='reconciliation_result')
    op.drop_index(op.f('ix_reconciliation_result_match_score'), table_name='reconciliation_result')
    op.drop_index(op.f('ix_reconciliation_result_manual_review_required'), table_name='reconciliation_result')
    op.drop_index(op.f('ix_reconciliation_result_id'), table_name='reconciliation_result')
    op.drop_index(op.f('ix_reconciliation_result_gstr2b_invoice_id'), table_name='reconciliation_result')
    op.drop_index(op.f('ix_reconciliation_result_created_at'), table_name='reconciliation_result')
    op.drop_index('ix_recon_result_status', table_name='reconciliation_result')
    op.drop_index('ix_recon_result_score', table_name='reconciliation_result')
    op.drop_index('ix_recon_result_review', table_name='reconciliation_result')
    op.drop_index('ix_recon_result_purchase', table_name='reconciliation_result')
    op.drop_index('ix_recon_result_gstr2b', table_name='reconciliation_result')
    op.drop_index('ix_recon_result_batch', table_name='reconciliation_result')
    op.drop_table('reconciliation_result')
    op.drop_index(op.f('ix_reconciliation_batch_user_id'), table_name='reconciliation_batch')
    op.drop_index(op.f('ix_reconciliation_batch_purchase_upload_id'), table_name='reconciliation_batch')
    op.drop_index(op.f('ix_reconciliation_batch_gstr2b_upload_id'), table_name='reconciliation_batch')
    op.drop_index('ix_recon_batch_user', table_name='reconciliation_batch')
    op.drop_index('ix_recon_batch_status', table_name='reconciliation_batch')
    op.drop_index('ix_recon_batch_purchase', table_name='reconciliation_batch')
    op.drop_index('ix_recon_batch_gstr2b', table_name='reconciliation_batch')
    op.drop_index('ix_recon_batch_created', table_name='reconciliation_batch')
    op.drop_table('reconciliation_batch')
    op.drop_index('ix_purchase_upload_matched', table_name='purchase_register_invoice')
    op.drop_index(op.f('ix_purchase_register_invoice_user_id'), table_name='purchase_register_invoice')
    op.drop_index(op.f('ix_purchase_register_invoice_upload_id'), table_name='purchase_register_invoice')
    op.drop_index(op.f('ix_purchase_register_invoice_supplier_gstin'), table_name='purchase_register_invoice')
    op.drop_index(op.f('ix_purchase_register_invoice_matched'), table_name='purchase_register_invoice')
    op.drop_index(op.f('ix_purchase_register_invoice_invoice_number_normalized'), table_name='purchase_register_invoice')
    op.drop_index(op.f('ix_purchase_register_invoice_invoice_number'), table_name='purchase_register_invoice')
    op.drop_index(op.f('ix_purchase_register_invoice_invoice_date'), table_name='purchase_register_invoice')
    op.drop_index(op.f('ix_purchase_register_invoice_id'), table_name='purchase_register_invoice')
    op.drop_index(op.f('ix_purchase_register_invoice_file_hash'), table_name='purchase_register_invoice')
    op.drop_index('ix_purchase_matched_status', table_name='purchase_register_invoice')
    op.drop_index('ix_purchase_gstin_invno_date', table_name='purchase_register_invoice')
    op.drop_table('purchase_register_invoice')
    op.drop_index('ix_gstr2b_upload_matched', table_name='gstr2b_invoice')
    op.drop_index('ix_gstr2b_matched_status', table_name='gstr2b_invoice')
    op.drop_index(op.f('ix_gstr2b_invoice_user_id'), table_name='gstr2b_invoice')
    op.drop_index(op.f('ix_gstr2b_invoice_upload_id'), table_name='gstr2b_invoice')
    op.drop_index(op.f('ix_gstr2b_invoice_matched'), table_name='gstr2b_invoice')
    op.drop_index(op.f('ix_gstr2b_invoice_invoice_number_normalized'), table_name='gstr2b_invoice')
    op.drop_index(op.f('ix_gstr2b_invoice_invoice_number'), table_name='gstr2b_invoice')
    op.drop_index(op.f('ix_gstr2b_invoice_invoice_date'), table_name='gstr2b_invoice')
    op.drop_index(op.f('ix_gstr2b_invoice_id'), table_name='gstr2b_invoice')
    op.drop_index(op.f('ix_gstr2b_invoice_gstin'), table_name='gstr2b_invoice')
    op.drop_index(op.f('ix_gstr2b_invoice_file_hash'), table_name='gstr2b_invoice')
    op.drop_index('ix_gstr2b_gstin_invno_date', table_name='gstr2b_invoice')
    op.drop_table('gstr2b_invoice')
    op.drop_index(op.f('ix_gstr2_configuration_user_id'), table_name='gstr2_configuration')
    op.drop_index(op.f('ix_gstr2_configuration_id'), table_name='gstr2_configuration')
    op.drop_index('ix_config_user', table_name='gstr2_configuration')
    op.drop_index('ix_config_default', table_name='gstr2_configuration')
    op.drop_table('gstr2_configuration')
    # ### end Alembic commands ###
